#Middle cords, set with /royalemiddle
midXcord: 0
midYcord: 0
midZcord: 0
groundY: 80
#Game periods (worldborder and loot)
periods:
  worldborder:
    - type: radius
      radius: 780
      time: 150
    - type: wait
      time: 100
    - type: radius
      radius: 600
      time: 150
    - type: wait
      time: 100
    - type: radius
      radius: 450
      time: 150
    - type: wait
      time: 100
    - type: radius
      radius: 75
      time: 120
    - type: wait
      time: 80
    - type: radius
      radius: 45
      time: 100
  loot:
    - type: airdrop
      time: 150
    - type: wait
      time: 120
    - type: airdrop
      time: 150
    - type: wait
      time: 120
    - type: airdrop
      time: 150
    - type: wait
      time: 120
    - type: airdrop
      time: 100
    - type: wait
      time: 150
    - type: airdrop
      time: 100