name: RoyaleEvent
version: 0.0.1
main: dev.hevav.royaleevent.RoyaleEvent
commands:
  royalemiddle:
    description: Set royale's middle point
    usage: /royalemiddle
    permission: royaleevent.admin
  royalestart:
    description: Start an event
    usage: /royalestart
    permission: royaleevent.start
  royalestop:
    description: Force stop event
    usage: /royalestop
    permission: royaleevent.admin
permissions:
  royaleevent.admin:
    default: op
    description: Admin rights for RoyaleEvent
  royaleevent.start:
    default: op
    description: Start rights for RoyaleEvent